station_schedule.settings:
  type: config_object
  label: 'Station schedule settings'
  mapping:
    current_schedule:
      type: integer
      label: 'The entity ID of the current schedule'
    provide_schedule_route:
      type: boolean
      label: 'Whether to provide a route to the current schedule at "/schedule"'
